# Conclusion {.unnumbered}

In summary, this project demonstrates how complex it is to hanlde missing data. The authors provide an end-to-end methodology to explore missing data, handling it using missing data methods, and analyze the impact of missing data methods on supervised analysis models. At the beginning of this text, the researchers proposed four key objectives: describe and visualize the extent of the missing value problem; examine factors related to missingness; develop methods to impute missing data; and measure the impact of imputation on inference derived from supervised learning. Throughout this text, the researchers addressed each objective. To address each objective, the researchers used Autoimpute - the open-source Python package the authors created for users grappling with missing data. The Autoimpute package provides methods to explore missingness, implement imputation methods, and analyze their impact on analytical models in a flexible way. 

This report focuses on establishing a solid foundation around the concepts missing data and imputation and demonstrates examples of missing data analysis on different types of missing data. Ultimately, this research provides Python-savy data practitioners a framework to use to explore missingness in their datasets, perform imputation methods, and assess the impact of imputation on analytical models downstream. Hopefully, users of the Autoimpute package are now well equipped to deal with missing data if and when it arises during their own machine learning research.

# Recommendations {.unnumbered}

This research explores missingness and outlines a framework through which a data practitioner can conduct missing data and imputation analysis. The researchers recommend data practitioners use the flexibility, simplicity, and granularity of the Autoimpute package to conduct their own missing data analyses. To start, data practitioners should review the Autoimpute tutorials website to get a better understanding of how the package works and how and end user can get the most out of its functionality. source code, either locally after a `pip install` or directly on Autoimpute's github page. Once familiar with the package, data practitioners should `pip install` the publicly available package from GitHub, review the source code, and start using the package in their own analysis. If challenges arise when using the package, researchers should contact the authors, preferably by submitting a bug report, feature request, or pull request depending on the nature of the issue. Lastly, the researchers hope end users share feedback about the Autoimpute package with the authors and share any interesting results found in personal analyses. 
